name: encurtei_ly
description: A new Flutter project.

version: 1.01.00+10100

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  google_sign_in: ^5.3.3
  hive: ^2.1.0
  lottie: ^1.2.2
  mocktail: ^0.3.0
  provider: ^6.0.2
 


dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/animations/
